from rootpath import *
from query import *
from setup import *
import os

print "start"

env=Environment()
print msvc_exists(env,'cl','6.0',arch='x86')
print msvc_exists(env,'ml')
print msvc_exists(env,'ml','9.0',arch='x86_64',strict=True)
print msvc_exists(env,'ml64','9.0',arch='x86_64',strict=True)
print msvc_exists(env,'cl')
print msvc_exists(env,'link')

setup_env(env,'8.0')
setup_env(env,'7.0')

#print msvc_exists(env,'ml',6.0)
#print msvc_exists(env,'cl',6.0)
#print msvc_exists(env,'link',6.0)


#print msvc_exists(env,'ml',8.0)
#print msvc_exists(env,'cl',8.0)
#print msvc_exists(env,'link',8.0)

##
##print "1)",msvs_root_dir(6.0)
##print "1)",msvc_root_dir(6.0)
##print "1)",msvs_default_root(6.0)
##print "1)",msvc_default_root(6.0)
##
##print "1)",msvs_default_root(7.0)
##print "1)",msvc_default_root(7.0)
##print "1)",msvs_root_dir(7.0)
##print "1)",msvc_root_dir(7.0)
##
##print "1)",msvs_root_dir(7.1)
##print "1)",msvs_default_root(7.1)
##print "1)",msvc_default_root(7.1)

#print "1)",msvs_root_dir(8.0)
#print "1)",msvs_default_root(8.0)
#print "1)",msvc_default_root(8.0)

#print "1)",msvs_root_dir(9.0)
#print "1)",msvs_default_root(9.0)
#print "1)",msvc_default_root(9.0)

#print "1)",msvs_root_dir(10.0)
#print "1)",msvs_default_root(10.0)
#print "1)",msvc_default_root(10.0)


##class version:
##    def __init__(self,val1):
##        import re
##        l = re.compile('v[0-9]+.*')
##        versions = filter(lambda e, l=l: l.match(e), [val1])
##        print val1,versions
##        
##
##v=version("1.3.6")

