from rootpath import *
from query import *
from setup import *
import os

print "start"

env=Environment()
##print msvc_exists(env,'cl','6.0',arch='x86')
##print msvc_exists(env,'cl','8.0')
##print msvc_exists(env,'ml')
##print msvc_exists(env,'ml','9.0',arch='x86_64',strict=True)
##print msvc_exists(env,'ml64','9.0',arch='x86_64',strict=True)
##print msvc_exists(env,'cl')
##print msvc_exists(env,'link')
##
setup_env(env.Clone(),'6.0',target_arch='x86')
setup_env(env.Clone(),'7.1',target_arch='x86')
setup_env(env.Clone(),'8.0')
setup_env(env.Clone())
#print env.Dump('ENV')
#setup_env(env,'7.0')

print msvc_exists(env,'ml','6.0',arch='x86')
print msvc_exists(env,'cl','6.0',arch='x86')
print msvc_exists(env,'link','6.0',arch='x86')


print msvc_exists(env,'ml','8.0')
print msvc_exists(env,'cl','8.0')
print msvc_exists(env,'link','8.0')



