import sys
import os
sys.path = [os.path.realpath(os.path.normpath('../..'))] + sys.path
from parts import *

LocalSetup()

Part(
    alias = 'regular_not_stripped',
    parts_file = 'regular_not_stripped.parts'
    )
Part(
    alias = 'shared_not_stripped',
    parts_file = 'shared_not_stripped.parts'
    )

Part(
    alias = 'regular_stripped',
    parts_file = 'regular_stripped.parts'
    )
Part(
    alias = 'shared_stripped',
    parts_file = 'shared_stripped.parts'
    )

Part(
    alias = 'regular_with_pdb',
    parts_file = 'regular_with_pdb.parts'
    )
Part(
    alias = 'shared_with_pdb',
    parts_file = 'shared_with_pdb.parts'
    )

Part(
    alias = 'invalid_pdb_usage_model',
    parts_file = 'invalid_pdb_usage_model.parts'
    )

Part(
    alias = 'advanced_strip_action',
    parts_file = 'advanced_strip_action.parts'
    )

Part(
    alias = 'advanced_pdb_action',
    parts_file = 'advanced_pdb_action.parts'
    )

Part(
    alias = 'regular_dep_on_shared_with_pdb',
    parts_file = 'regular_dep_on_shared_with_pdb.parts'
    )

# vim: set et ts=4 sw=4 ft=python :

