#################
# for easy testing
import sys
sys.path = ['../../']+sys.path
##############

from parts import *

Part('a_alias', 'a.parts')

#print DefaultEnvironment().Dump('PART_INFO')
#print DefaultEnvironment().Dump('PART_IDS')